# src/main/resources/log4j2.properties
rootLogger.level = INFO
rootLogger.appenderRef.console.ref = ConsoleAppender

appender.console.name = ConsoleAppender
appender.console.type = CONSOLE
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,SSS} %-5p %-60c %x - %m%n

logger.flink.name = org.apache.flink
logger.flink.level = WARN

logger.kafka.name = org.apache.kafka
logger.kafka.level = WARN

logger.taxi.name = com.taxi.realtime
logger.taxi.level = DEBUG